const {taxiFee} = require("./taxiFee");

test('タクシー料金が適切かテスト', () => { 
    expect(taxiFee("ADFC")).toBe(510)
    expect(taxiFee("CFDA")).toBe(500)
    expect(taxiFee("AB")).toBe(460)
    expect(taxiFee("BA")).toBe(460)
    expect(taxiFee("CD")).toBe(400)
    expect(taxiFee("DC")).toBe(350)
    expect(taxiFee("BG")).toBe(520)
    expect(taxiFee("GB")).toBe(530)
    expect(taxiFee("FDA")).toBe(450)
    expect(taxiFee("ADF")).toBe(450)
    expect(taxiFee("FDACB")).toBe(750)
    expect(taxiFee("BCADF")).toBe(710)
    expect(taxiFee("EDACB")).toBe(800)
    expect(taxiFee("BCADE")).toBe(810)
    expect(taxiFee("EGFCADE")).toBe(920)
    expect(taxiFee("EDACFGE")).toBe(910)
    expect(taxiFee("ABCDA")).toBe(960)
    expect(taxiFee("ADCBA")).toBe(1000)
    expect(taxiFee("BADCFGB")).toBe(1180)
    expect(taxiFee("BGFCDAB")).toBe(1180)
    expect(taxiFee("CDFC")).toBe(460)
    expect(taxiFee("CFDC")).toBe(450)
    expect(taxiFee("ABGEDA")).toBe(1420)
    expect(taxiFee("ADEGBA")).toBe(1470)
    expect(taxiFee("CFGB")).toBe(640)
    expect(taxiFee("BGFC")).toBe(630)
    expect(taxiFee("ABGEDFC")).toBe(1480)
    expect(taxiFee("CFDEGBA")).toBe(1520)
    expect(taxiFee("CDFGEDABG")).toBe(1770)
    expect(taxiFee("GBADEGFDC")).toBe(1680)
})